### ISSUE TITLE
c++ code for 07 November 2024

### ISSUE THREAD

**Issue by Divyanshu-RS** [Hunterdii/GeeksforGeeks-POTD#16]
class Solution {
public:
    vector<int> findSplit(vector<int>& arr) {
        int total_sum = 0;
        for (int num : arr) {
            total_sum += num;
        }
        
        if (total_sum % 3 != 0) {
            return {-1, -1};
        }
        
        int target_sum = total_sum / 3;
        int current_sum = 0;
        int first_index = -1, second_index = -1;
        int n = arr.size();
        
        for (int i = 0; i < n; i++) {
            current_sum += arr[i];
            
            if (current_sum == target_sum && first_index == -1) {
                first_index = i;
            }
            
            if (current_sum == 2 * target_sum && first_index != -1) {
                second_index = i;
                break;
            }
        }
        
        if (first_index != -1 && second_index != -1) {
            int last_part_sum = 0;
            for (int i = second_index + 1; i < n; i++) {
                last_part_sum += arr[i];
            }
            if (last_part_sum == target_sum) {
                return {first_index, second_index};
            }
        }
        
        return {-1, -1};
    }
};

**Comment by Hunterdii** [comment]
Is my code of todays potd not working or is ur code more optimize tell me or directly add an pull request for the same if any problem is their

**Comment by Divyanshu-RS** [comment]
Dear your code is not working, so I have worked on mine, its optimized

**Comment by Hunterdii** [comment]
## Code (C++)

```cpp
class Solution {
public:
    vector<int> findSplit(vector<int>& arr) {
        int n = arr.size();
        int totalSum = accumulate(arr.begin(), arr.end(), 0);

        if (totalSum % 3 != 0)
            return {-1, -1};

        int target = totalSum / 3;
        int currentSum = 0;
        int countFirst = 0;  

        for (int i = 0; i < n; ++i) {
            currentSum += arr[i];

            if (currentSum == 2 * target && countFirst > 0)
                return {countFirst - 1, i};  

            if (currentSum == target) {
                countFirst++;  
            }
        }

        return {-1, -1};
    }
};
```
is this not working tell me can u again try it because mine it is properly working

**Comment by Hunterdii** [comment]
Can u please edit it and make pull please because im out otherwise ill change it ok 
If not tell me ill do it in few minutes

**Comment by Divyanshu-RS** [comment]
if I am going with this code I am having following error 
![Screenshot 2024-11-07 203209](https://github.com/user-attachments/assets/08fbf0ed-7c77-4acd-a24e-90f1dbc3274d)

**Comment by Hunterdii** [comment]
Yup sorry on uploading code changes how i don’t very sorry can u make a pull and resolve add with ur solution or ill do it wait for little minutes 
## Thanks for telling and making issue good

**Comment by Divyanshu-RS** [comment]
Yup!! Now all the codes are working perfectly & fine.
